# Configuration file for a Based RAG (Retrieval-Augmented Generation) system

name: "<name_of_your_rag>"
type: base

components:
  embeddings:
    name: 
    parmas:
  chat_models:
    name: 
    params:
  vector_stores:
    name: 
    params:
  loader:
    name: 
    params:
  text_splitter:
    name: 
    params:

retriever_parmas: