# docker-compose --env-file .env up
# use --remove-orphans to remove containers that are not defined in the docker-compose.yml file
version: '3.8'

services:

  langchain_rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain_rag
    environment:
      APP_PORT: ${APP_PORT}
      CHROMA_HOST: ${CHROMA_HOST}
      CHROMA_PORT: ${CHROMA_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    command: python . 
    networks:
     - app_network

  chroma_db:
    image: chromadb/chroma:0.6.4.dev411
    container_name: chroma_db
    ports:
      - ${CHROMA_PORT}:${CHROMA_PORT}
    volumes:
      - ./chroma_data:/data
    networks:
      - app_network


networks:
  app_network:
    driver: bridge