# Configuration file for a Based RAG (Retrieval-Augmented Generation) system

components:
  embeddings:
    name: 
    params:
  chat_models:
    name: 
    params:
  vectore_store:
    name: 
    params:
  loader:
    name: 
    params:
  text_splitter:
    name: 
    params:

retriever_params:

preproces:

system_prompt_file: