# Configuration file for a Based RAG (Retrieval-Augmented Generation) system

components:
  embeddings:
    name: bge_small
    params:
  chat_models:
    name: gpt35_turbo
    params:
  vectore_store:
    name: chroma
    params:
      collection_name: my_first_rag_collection
      host_client: ${{ CHROMA_HOST }}
      port_client: ${{ CHROMA_PORT }}
  loader:
    name: document_loader
    params:
      path: ./docs
  text_splitter:
    name: recursive_character_text_splitter
    params:
      chunk_size: 1000
      chunk_overlap: 200

retriever_params:
  search_type: "similarity" 
  top_k: 5

preproces:
  text: 
    name: "clean"
    params:

system_prompt_file: rag/base/system_prompts/timeline.txt
